using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersion("$(BUILD_NUMBER)")]
[assembly: AssemblyFileVersion("3.1.1")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aqueduct 2007-2012")]
[assembly: AssemblyCompanyAttribute("Aqueduct")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyInformationalVersion("1.0.0-f0b71e8")]